### ISSUE TITLE
Mac OS: Create New Wallet fails

### ISSUE THREAD

**Issue by Grandiose** [fastepic/epicwallet#7]
crashes command line with "permission denied" error when trying to first create wallet:

Wolverines-MBP:EpicWallet Wolverinelogan$ ./EpicStart
Start Epic Wallet. Look at your web browser !
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /Users/Wolverinelogan/Desktop/EpicWallet
Unhandled exception. System.ComponentModel.Win32Exception (13): Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at NetCore.EpicWallet.startProcesEpic(String command, String pass, Boolean usepass, String texttosearch, Boolean usesearch) in /Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs:line 1692
   at NetCore.EpicWallet.Words(String pass) in /Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs:line 1062
   at NetCore.Startup.CheckWhat(FromPage frompage, HttpResponse Response) in /Users/Wolverinelogan/Desktop/Git/epicwallet/Startup.cs:line 660
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Abort trap: 6
Wolverines-MBP:EpicWallet Wolverinelogan$

**Comment by Grandiose** [comment]
I recompiled the wallet and added "sudo" at the beginning of the command.  So the compile command is now like this:

sudo dotnet publish --configuration Release --runtime osx-x64 --self-contained true /p:PublishTrimmed=true

The error output changed when trying to setup the first-time wallet.  No longer says "Permission denied"  Now says "No such file or directory"

New error output:

Unhandled exception. System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at NetCore.EpicWallet.startProcesEpic(String command, String pass, Boolean usepass, String texttosearch, Boolean usesearch) in /Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs:line 1692
   at NetCore.EpicWallet.Words(String pass) in /Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs:line 1055
   at NetCore.Startup.CheckWhat(FromPage frompage, HttpResponse Response) in /Users/Wolverinelogan/Desktop/Git/epicwallet/Startup.cs:line 660
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by Grandiose** [comment]
I recompiled as "sudo" and there was no change

**Comment by Grandiose** [comment]
Somewhat different error:

Unhandled exception. System.ComponentModel.Win32Exception (13): Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at NetCore.EpicWallet.startProcesEpic(String command, String pass, Boolean usepass, String texttosearch, Boolean usesearch) in /Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs:line 1692
   at NetCore.EpicWallet.Words(String pass) in /Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs:line 1055
   at NetCore.Startup.CheckWhat(FromPage frompage, HttpResponse Response) in /Users/Wolverinelogan/Desktop/Git/epicwallet/Startup.cs:line 660
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Abort trap: 6

**Comment by Grandiose** [comment]
This is the report after doing the compile:


Wolverines-MBP:epicwallet Wolverinelogan$ sudo dotnet publish --configuration Release --runtime osx-x64 --self-contained true /p:PublishTrimmed=true

Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /Users/Wolverinelogan/Desktop/Git/epicwallet/NetCore.csproj (in 111 ms).
/Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs(101,12): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call. [/Users/Wolverinelogan/Desktop/Git/epicwallet/NetCore.csproj]
/Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs(389,35): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [/Users/Wolverinelogan/Desktop/Git/epicwallet/NetCore.csproj]
/Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs(448,35): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [/Users/Wolverinelogan/Desktop/Git/epicwallet/NetCore.csproj]
/Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs(506,35): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [/Users/Wolverinelogan/Desktop/Git/epicwallet/NetCore.csproj]
/Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs(601,22): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [/Users/Wolverinelogan/Desktop/Git/epicwallet/NetCore.csproj]
/Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs(882,11): warning CS0219: The variable 'odp' is assigned but its value is never used [/Users/Wolverinelogan/Desktop/Git/epicwallet/NetCore.csproj]
/Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs(947,27): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [/Users/Wolverinelogan/Desktop/Git/epicwallet/NetCore.csproj]
/Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs(975,29): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [/Users/Wolverinelogan/Desktop/Git/epicwallet/NetCore.csproj]
/Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs(1026,13): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call. [/Users/Wolverinelogan/Desktop/Git/epicwallet/NetCore.csproj]
/Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs(1118,33): warning CS0168: The variable 'e' is declared but never used [/Users/Wolverinelogan/Desktop/Git/epicwallet/NetCore.csproj]
/Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs(1129,35): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [/Users/Wolverinelogan/Desktop/Git/epicwallet/NetCore.csproj]
/Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs(1161,33): warning CS0168: The variable 'e' is declared but never used [/Users/Wolverinelogan/Desktop/Git/epicwallet/NetCore.csproj]
/Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs(1197,33): warning CS0168: The variable 'e' is declared but never used [/Users/Wolverinelogan/Desktop/Git/epicwallet/NetCore.csproj]
/Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs(1232,33): warning CS0168: The variable 'e' is declared but never used [/Users/Wolverinelogan/Desktop/Git/epicwallet/NetCore.csproj]
/Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs(1260,33): warning CS0168: The variable 'e' is declared but never used [/Users/Wolverinelogan/Desktop/Git/epicwallet/NetCore.csproj]
/Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs(1244,35): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [/Users/Wolverinelogan/Desktop/Git/epicwallet/NetCore.csproj]
/Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs(1285,38): warning CS0168: The variable 'e' is declared but never used [/Users/Wolverinelogan/Desktop/Git/epicwallet/NetCore.csproj]
/Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs(1271,33): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [/Users/Wolverinelogan/Desktop/Git/epicwallet/NetCore.csproj]
/Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs(1330,33): warning CS0168: The variable 'e' is declared but never used [/Users/Wolverinelogan/Desktop/Git/epicwallet/NetCore.csproj]
/Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs(1376,33): warning CS0168: The variable 'e' is declared but never used [/Users/Wolverinelogan/Desktop/Git/epicwallet/NetCore.csproj]
/Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs(1341,35): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [/Users/Wolverinelogan/Desktop/Git/epicwallet/NetCore.csproj]
/Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs(1446,19): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call. [/Users/Wolverinelogan/Desktop/Git/epicwallet/NetCore.csproj]
/Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs(1456,27): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [/Users/Wolverinelogan/Desktop/Git/epicwallet/NetCore.csproj]
/Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs(1818,33): warning CS0168: The variable 'e' is declared but never used [/Users/Wolverinelogan/Desktop/Git/epicwallet/NetCore.csproj]
/Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs(1889,33): warning CS0168: The variable 'e' is declared but never used [/Users/Wolverinelogan/Desktop/Git/epicwallet/NetCore.csproj]
/Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs(1992,33): warning CS0168: The variable 'e' is declared but never used [/Users/Wolverinelogan/Desktop/Git/epicwallet/NetCore.csproj]
/Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs(2085,33): warning CS0168: The variable 'e' is declared but never used [/Users/Wolverinelogan/Desktop/Git/epicwallet/NetCore.csproj]
/Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs(2108,33): warning CS0168: The variable 'e' is declared but never used [/Users/Wolverinelogan/Desktop/Git/epicwallet/NetCore.csproj]
/Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs(2156,33): warning CS0168: The variable 'e' is declared but never used [/Users/Wolverinelogan/Desktop/Git/epicwallet/NetCore.csproj]
/Users/Wolverinelogan/Desktop/Git/epicwallet/epicwallet.cs(2184,29): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [/Users/Wolverinelogan/Desktop/Git/epicwallet/NetCore.csproj]
/Users/Wolverinelogan/Desktop/Git/epicwallet/Startup.cs(26,51): warning CS0169: The field 'Startup._appLifetime' is never used [/Users/Wolverinelogan/Desktop/Git/epicwallet/NetCore.csproj]
  NetCore -> /Users/Wolverinelogan/Desktop/Git/epicwallet/bin/Release/net5.0/osx-x64/NetCore.dll
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
  NetCore -> /Users/Wolverinelogan/Desktop/Git/epicwallet/bin/Release/net5.0/osx-x64/publish/
